### ISSUE TITLE
Undefined constant "Syncrasy\PimcoreSalesforceBundle\Services\SOAP_SINGLE_ELEMENT_ARRAYS"

### ISSUE THREAD

**Issue by wumi20** [syncrasy-git/Pimcore-Salesforce-Connector#4]
Hi 

When the buddle is installed, there's an error message like this,would you please help what went wrong here? Thanks

Status: 500 | 
URL: /admin/pimcoresalesforce/default/sf-object?_dc=1702128285377
Method: GET
Message: Undefined constant "Syncrasy\PimcoreSalesforceBundle\Services\SOAP_SINGLE_ELEMENT_ARRAYS"
Trace: 
in /mnt/sftp/mysftp/upload/turbopim/pimcore/vendor/syncrasy/pimcore-salesforce-bundle/Services/SforceBaseClient.php:78
#0 /mnt/sftp/mysftp/upload/turbopim/pimcore/vendor/syncrasy/pimcore-salesforce-bundle/Services/Sfconnect.php(34): Syncrasy\PimcoreSalesforceBundle\Services\SforceBaseClient->createConnection()
#1 /mnt/sftp/mysftp/upload/turbopim/pimcore/vendor/syncrasy/pimcore-salesforce-bundle/Services/Sfconnect.php(25): Syncrasy\PimcoreSalesforceBundle\Services\Sfconnect->authenticate()
#2 /mnt/sftp/mysftp/upload/turbopim/pimcore/vendor/syncrasy/pimcore-salesforce-bundle/Controller/DefaultController.php(78): Syncrasy\PimcoreSalesforceBundle\Services\Sfconnect->__construct()
#3 /mnt/sftp/mysftp/upload/turbopim/pimcore/vendor/symfony/http-kernel/HttpKernel.php(163): Syncrasy\PimcoreSalesforceBundle\Controller\DefaultController->getSfObjectAction()
#4 /mnt/sftp/mysftp/upload/turbopim/pimcore/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#5 /mnt/sftp/mysftp/upload/turbopim/pimcore/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle()
#6 /mnt/sftp/mysftp/upload/turbopim/pimcore/public/index.php(36): Symfony\Component\HttpKernel\Kernel->handle()
#7 {main}

**Comment by syncrasy-git** [comment]
@wumi20 Can you please tell me the Pimcore version?

**Comment by wumi20** [comment]
@syncrasy-git I am using pimcore v10.5.20
